general:
  backend: default                  # The matploblib backend used for visualization. `default` uses the system default, can specifiy specific backend (e.g. TKAgg, Qt5Agg, WXAgg).
  imshow_origin: upper              # The `origin` input of `imshow`, determining if pixel values are ascending or descending on the y-axis.
  zoom_around_mask: true            # If True, plots of data structures with a mask automatically zoom in the masked region.
  symmetric_cmap_value: 100.0       # The vmin and vmax of all pre-cti data residual-maps.
  subplot_ascending_fpr: true       # If True, subplots showing FPR / EPER trails of many datasets are in ascending order of FPR value.
subplot_shape:                      # The shape of a subplots for figures with an input number of subplots (e.g. for a figure with 4 subplots, the shape is (2, 2)).
  2: (1, 2)                         # The shape of subplots for a figure with 2 subplots.
  4: (1, 4)                         # The shape of subplots for a figure with 4 (or less than the above value) of subplots.
  6: (2, 3)                         # The shape of subplots for a figure with 6 (or less than the above value) of subplots.
  8: (2, 4)                         # The shape of subplots for a figure with 8 (or less than the above value) of subplots.
  9: (3, 3)                         # The shape of subplots for a figure with 9 (or less than the above value) of subplots.
  12: (3, 4)                        # The shape of subplots for a figure with 12 (or less than the above value) of subplots.
  16: (4, 4)                        # The shape of subplots for a figure with 16 (or less than the above value) of subplots.
  20: (5, 4)                        # The shape of subplots for a figure with 20 (or less than the above value) of subplots.
  24: (6, 4)                        # The shape of subplots for a figure with 24 (or less than the above value) of subplots.
  28: (7, 4)                        # The shape of subplots for a figure with 28 (or less than the above value) of subplots.
  32: (8, 4)                        # The shape of subplots for a figure with 32 (or less than the above value) of subplots.
  36: (9, 4)                        # The shape of subplots for a figure with 36 (or less than the above value) of subplots.
  40: (10, 4)                       # The shape of subplots for a figure with 40 (or less than the above value) of subplots.
  49: (7, 7)                        # The shape of subplots for a figure with 49 (or less than the above value) of subplots.
  64: (16, 4)                        # The shape of subplots for a figure with 64 (or less than the above value) of subplots.
  81: (9, 9)                        # The shape of subplots for a figure with 81 (or less than the above value) of subplots.
  100: (10, 10)                     # The shape of subplots for a figure with 100 (or less than the above value) of subplots.
subplot_shape_to_figsize_factor: (6, 6) # The factors by which the subplot_shape is multiplied to determine the figsize of a subplot (e.g. if the subplot_shape is (2,2), the figsize will be (2*6, 2*6).
units:
  use_scaled: false                 # Whether to plot spatial coordinates in scaled units computed via the pixel_scale (e.g. arc-seconds) or pixel units by default.
  scaled_symbol: '"'                    # The symbol used when plotting spatial coordinates computed via the pixel_scale (e.g. for Astronomy data this is arc-seconds).
  unscaled_symbol: pix                  # The symbol used when plotting spatial coordinates in unscaled pixel units.
  cb_unit: $\,\,\mathrm{e^{-}}$ # The string or latex unit label used for the colorbar of the image, for example electrons.
